# Generated by Django 3.1.7 on 2021-03-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='left',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='right',
            field=models.IntegerField(null=True),
        ),
    ]
