# Generated by Django 3.1.7 on 2021-03-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210330_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='count',
            new_name='number',
        ),
        migrations.AddField(
            model_name='game',
            name='optinB_image',
            field=models.ImageField(null=True, upload_to='games/'),
        ),
        migrations.AddField(
            model_name='game',
            name='optionA_image',
            field=models.ImageField(null=True, upload_to='games/'),
        ),
    ]
