# Generated by Django 3.1.7 on 2021-03-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20210330_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='optinB_image',
            new_name='optionB_image',
        ),
    ]
