# Generated by Django 3.1.7 on 2021-03-31 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_like_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like_user',
            new_name='like_users',
        ),
    ]
