# Generated by Django 3.1.7 on 2021-03-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20210330_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='left',
        ),
        migrations.RemoveField(
            model_name='game',
            name='right',
        ),
        migrations.AlterField(
            model_name='game',
            name='optinB_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='optionA_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
