# Generated by Django 3.1.7 on 2021-03-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20210330_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='optinB_image',
            field=models.ImageField(blank=True, upload_to='games/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='optionA_image',
            field=models.ImageField(blank=True, upload_to='games/'),
        ),
    ]
